# Generated by Django 4.1.3 on 2022-12-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_story_author_alter_story_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.story'),
        ),
    ]
