# Generated by Django 4.1.3 on 2022-12-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_story_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date_updated', '-date_created']},
        ),
    ]
