# Generated by Django 4.1.3 on 2022-12-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('politices', 'male'), ('sport', 'sport'), ('christain', 'christain'), ('others', 'others')], default='christain', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
