# Generated by Django 4.1.3 on 2022-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_story_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('christain', 'christain'), ('sport', 'sport'), ('politices', 'politics'), ('tech', 'tech'), ('others', 'others')], default='christain', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
