# Generated by Django 4.1.3 on 2022-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='img',
            field=models.ImageField(default='default.png', upload_to='cards_pics'),
        ),
    ]
