# Generated by Django 4.1.3 on 2022-12-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='start_date',
            new_name='dob',
        ),
    ]
